-- CREATE TABLE products(
-- 	id INT AUTO_INCREMENT PRIMARY KEY,
--     image_base64 LONGTEXT,
--     title VARCHAR(250) NOT NULL,
--     price DECIMAL(10, 2) NOT NULL,
--     stock INT NOT NULL,
--     description TEXT NOT NULL,
--     category VARCHAR(40),
--     seller_id INT NOT NULL,
--     active BOOLEAN DEFAULT TRUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--     )